### ISSUE TITLE
Lab experiments in MXNet

### ISSUE THREAD

**Issue by sxjscience** [hunkim/DeepLearningZeroToAll#107]
I decide to add the following 7 lab experiments implemented in MXNet.
Also, all the scripts will be tested against the latest MXNet master.

TODOs
-------
Basic
- [x]  Lab 4-3
- [x]  Lab 5-2
- [x]  Lab 6-2
- [x]  Lab 11-2
- [x]  Lab 11-5
- [x]  Lab 12-4
- [x]  Lab 12-5

Advanced
- [ ] Spatial Transformer Network
- [ ] GAN that fits a mixture of Gaussian

**Comment by hunkim** [comment]
Thanks!

**Comment by sxjscience** [comment]
The seq2seq learning example of MXNet is magnitudes faster than Keras with the same network structure. @kkweon @skyer9 would you like to check the result again?

The scripts are `python mxnet\\mxlab-12-5-seq2seq.py` and `python keras\\klab-12-5-seq2seq.py`. I'm not familiar with Keras and TF so it would be much better if someone that is more experienced to run these experiments again.

For MXNet, I'm using the latest master version. For Keras, i'm using keras 2.0.3 + tensorflow 1.0.1
