### ISSUE TITLE
refactoring MinMaxScaler

### ISSUE THREAD

**Issue by kkweon** [hunkim/DeepLearningZeroToAll#109]
# Summary
* Currently, two types of `MinMaxScaler`s are used inconsistently
* It's not consistent
* Let's choose one and fix !

## Type 1: using sklearn

```python
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0, 1))
xy = scaler.fit_transform(xy)
```
### Problems
1. it creates another dependency on `sklearn`

## Type 2: custom defined function

```python
import numpy as np

def MinMaxScaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

xy = MinMaxScaler(xy)
```
### Problems
1. Instead of `MinMaxScaler`, it should be named as `min_max_scaler(data)` since it's a function.
2. It takes multiples lines every time we use it (maybe create an `utils.py` ?)

## Relevent files
* lab-07-3-linear_regression_min_max.py
* lab-12-5-rnn_stock_prediction.py
* Keras/klab-04-4-stock_linear_regression.py
* Keras/klab-12-3-rnn_stock_prediction.py
* Keras/klab-12-4-rnn_deep_prediction.py
* PyTorch/lab-12-5-stock_prediction.py

**Comment by hunkim** [comment]
+1 for Type 1. Also, I used this for KaggleZeroToAll.

**Comment by kkweon** [comment]
Since this is easy to fix, I will leave it open for beginners. Please post here if anyone wants to tackle this.
