### ISSUE TITLE
Small typo in lab-01-basics.ipynb

### ISSUE THREAD

**Issue by SDRLurker** [hunkim/DeepLearningZeroToAll#123]
# Problem
There is a typo in [lab-01-basics.ipynb correction](https://github.com/hunkim/DeepLearningZeroToAll/blob/master/lab-01-basics.ipynb).

![typo](https://cloud.githubusercontent.com/assets/2981167/25068187/3db096ce-2210-11e7-8afa-d8080130c1bf.png)

# Fix
* `# seart a TF session` -> `# start a TF session`

**Comment by hunkim** [comment]
@SDRLurker Nice. Can you send us a PR?

**Comment by chg0901** [comment]
@kkweon  @hunkim  I modify this typo a few minutes ago

**Comment by SDRLurker** [comment]
This pull request is the first time. So, I need to study how to pull request.
