### ISSUE TITLE
supplement code for "Out of Memory" issue

### ISSUE THREAD

**Issue by nicewook** [hunkim/DeepLearningZeroToAll#130]
file: lab-11-2-mnist_deep_cnn.py

mnist.test data set is too big for some system so that makes Out of Memory issue.
**"ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[10000,32,28,28]"**

I think it would be good to provide supplement code in comment

**Comment by hunkim** [comment]
Thanks for reporting this. Do you have any solution?

**Comment by nicewook** [comment]
I pull requested already. 
frankly speaking, this is my practice for "issuing and pull requesting" too. 
so, if it's not fit for this repo's policy, it's okey to pass the pull request. :-)
