### ISSUE TITLE
lab-12-4-rnn_long_char ValueError

### ISSUE THREAD

**Issue by JAICHANGPARK** [hunkim/DeepLearningZeroToAll#142]
outputs, _states = tf.nn.dynamic_rnn(cell, X_one_hot, dtype=tf.float32)
X_for_fc = tf.reshape(outputs, [-1, hidden_size])
outputs = tf.contrib.layers.fully_connected(X_for_fc, num_classes, activation_fn=None)
outputs = tf.reshape(outputs, [batch_size, sequence_length, num_classes])

> ValueError: Attempt to reuse RNNCell <tensorflow.contrib.rnn.python.ops.core_rnn_cell_impl.BasicLSTMCell object at 0x00000256226FEC50> with a different variable scope than its first use.  First use of cell was with scope 'rnn/multi_rnn_cell/cell_0/basic_lstm_cell', this attempt is with scope 'rnn/multi_rnn_cell/cell_1/basic_lstm_cell'.  Please create a new instance of the cell if you would like it to use a different set of weights.  If before you were using: MultiRNNCell([BasicLSTMCell(...)] * num_layers), change to: MultiRNNCell([BasicLSTMCell(...) for _ in range(num_layers)]).  If before you were using the same cell instance as both the forward and reverse cell of a bidirectional RNN, simply create two instances (one for forward, one for reverse).  In May 2017, we will start transitioning this cell's behavior to use existing stored weights, if any, when it is called with scope=None (which can lead to silent model degradation, so this error will remain until then.)

**Comment by JAICHANGPARK** [comment]
> ValueError: Attempt to have a second RNNCell use the weights of a variable scope that already has weights: 'rnn/multi_rnn_cell/cell_0/basic_lstm_cell'; and the cell was not constructed as BasicLSTMCell(..., reuse=True).  To share the weights of an RNNCell, simply reuse it in your second calculation, or create a new one with the argument reuse=True.

**Comment by kkweon** [comment]
![fff](https://cloud.githubusercontent.com/assets/2981167/25562477/7ac53d36-2d3b-11e7-88fc-cfbbe911978f.png)

I'm not able to reproduce this error.

What is your tensorflow version?  tested on OSX & Linux with tf.version 1.0.1
```bash
python -c "import tensorflow; print(tensorflow.__version__)"
```

**Comment by hunkim** [comment]
I also cannot reproduce. Please let me know.

@JAICHANGPARK are you running this on Jupiter notebook?

**Comment by antil1** [comment]
This error occur on google cloud platform. (Ubuntu 16.04LTS, Tensorflow(1.1.0))
