### ISSUE TITLE
convert py to ipynb

### ISSUE THREAD

**Issue by FuZer** [hunkim/DeepLearningZeroToAll#15]
.py 파일을 .ipynb로 변환하려고 합니다. 
혹시 다른 분 중에서 변환을 진행 중이거나 
변환 목록 등이 있나요?

**Comment by hunkim** [comment]
Thanks! I'd like to get code reviews on py files first. Then, you can help us to port them to ipynb next week. Could you check py files and they are OK?

**Comment by FuZer** [comment]
네 :)
