### ISSUE TITLE
텐서플로 설치했는데 왜 인식이 안되는지 모르겠습니다.

### ISSUE THREAD

**Issue by Jake132456** [hunkim/DeepLearningZeroToAll#171]
지금 현재 아나콘다 프롬프트로 텐서플로 활성화 후에 파이썬으로 들어가서 import tensorflow as tf하면 잘 됩니다.
그런데 atom에서 코드 실행하면 노 모듈네임드 텐서플로 뜹니다.
그러면서 헬로 텐서플로가 실행이 안 됩니다.
그리고 리니어리그레션 과정 붙여넣기 하면 cmd에서도 안되고 atom에서도 안 됩니다.
인스톨은 1.0버전이 되어있고요.
왜 안되는지 아시는 분 있으신가요?
너무 답답하네요.
윈도우 10 쓰고 있습니다.

**Comment by kkweon** [comment]
파이썬 여러대가 설치 되어 있는 것 같군요.
아톰에서 파이썬은 아마 아톰이랑 같이 온 파이썬이나 다른 파이썬 깔려 있는것 같네요.

기본적으로 모든 실행 커맨드는 환경변수(PATH)에서 검색을 합니다
cmd에서 python이라고 치면 그 python을 어떻게 찾을까요
환경 변수(PATH)에있는 경로들 중에서 찾아서 가장 먼저 찾은 것이 실행됩니다.

atom에서 python을 실행시킬때 오류가 나온다는 얘기는 atom이 실행시킨 python이랑 
테스트하신 python이랑 다르다는 뜻입니다. 
즉 atom에서는 다른 PATH의 python을 실행시킨 것이구요.

atom에서 파이썬 경로 설정하는 부분을 잘 보시고 왜 여러대가 설치되었는지 확인해보세요.

안되는 것은 왜 안되는지 정확히 적어주시길 바랍니다.
시간 되시면 "질문하는 방법" https://kldp.org/node/136925 이런 글을 읽어보세요.
