### ISSUE TITLE
전에 텐서플로우 아톰에서 인식 안 됬다고 글 올렸던 사람입니다.

### ISSUE THREAD

**Issue by Jake132456** [hunkim/DeepLearningZeroToAll#172]
아나콘다 프롬프트에서는 텐서플로가 되고 아톰에서는 안 된다고 글을 오렸는데요.
제가 파이썬이 여러개여서 아나콘다 프롬프트에서는 텐서플로가 되고 아톰에서는 안되는 이유가 파이썬이 여러개 깔려 있어서 그렇다는 설명을 들었습니다.
제가 한참을 생각해본 결과 파이썬을 공식 홈페이지에서 다운 받아서 설치했다가 제어판을 통해서 지우고 다시 아나콘다를 깔았습니다.
아마 그것때문에 문제가 되지 않나 싶은데 공식 홈페이지 파이썬 어떻게 깨끗하게 삭제할 수 있을까요?

**Comment by kkweon** [comment]
github issue는 해당 repo와 관련된 이슈사항을 기록하는 곳입니다.

1. https://www.facebook.com/groups/TensorFlowKR/
2. stackoverflow
3. 구글
에 질문을 올려보시는게 더 빨리 답을 얻으 실 것 같습니다 ^^
