### ISSUE TITLE
12-5-rnn has compile error at making dynamic_rnn

### ISSUE THREAD

**Issue by ryukidong** [hunkim/DeepLearningZeroToAll#177]
lab-12-5-rnn_stock_prediction.py
I try to run this code, but it has error. 
My TF' version is 1.1.0, 

outputs, _states = tf.nn.dynamic_rnn(cell, X, dtype=tf.float32)

===============================================================
ValueError                                Traceback (most recent call last)
<ipython-input-57-ce45fe4d8f4e> in <module>()
      2 cell = tf.contrib.rnn.BasicLSTMCell(
      3     num_units=hidden_dim, state_is_tuple=True, activation=tf.tanh)
----> 4 outputs, _states = tf.nn.dynamic_rnn(cell, X, dtype=tf.float32)

C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\rnn.py in dynamic_rnn(cell, inputs, sequence_length, initial_state, dtype, parallel_iterations, swap_memory, time_major, scope)
    551         swap_memory=swap_memory,
    552         sequence_length=sequence_length,
--> 553         dtype=dtype)
    554 
    555     # Outputs of _dynamic_rnn_loop are always shaped [time, batch, depth].

C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\rnn.py in _dynamic_rnn_loop(cell, inputs, initial_state, parallel_iterations, swap_memory, sequence_length, dtype)
    718       loop_vars=(time, output_ta, state),
    719       parallel_iterations=parallel_iterations,
--> 720       swap_memory=swap_memory)
    721 
    722   # Unpack final output if not using output tuples.

C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\control_flow_ops.py in while_loop(cond, body, loop_vars, shape_invariants, parallel_iterations, back_prop, swap_memory, name)
   2621     context = WhileContext(parallel_iterations, back_prop, swap_memory, name)
   2622     ops.add_to_collection(ops.GraphKeys.WHILE_CONTEXT, context)
-> 2623     result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
   2624     return result
   2625 

C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\control_flow_ops.py in BuildLoop(self, pred, body, loop_vars, shape_invariants)
   2454       self.Enter()
   2455       original_body_result, exit_vars = self._BuildLoop(
-> 2456           pred, body, original_loop_vars, loop_vars, shape_invariants)
   2457     finally:
   2458       self.Exit()

C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\control_flow_ops.py in _BuildLoop(self, pred, body, original_loop_vars, loop_vars, shape_invariants)
   2404         structure=original_loop_vars,
   2405         flat_sequence=vars_for_body_with_tensor_arrays)
-> 2406     body_result = body(*packed_vars_for_body)
   2407     if not nest.is_sequence(body_result):
   2408       body_result = [body_result]

C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\rnn.py in _time_step(time, output_ta_t, state)
    703           skip_conditionals=True)
    704     else:
--> 705       (output, new_state) = call_cell()
    706 
    707     # Pack state if using state tuples

C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\rnn.py in <lambda>()
    689 
    690     input_t = nest.pack_sequence_as(structure=inputs, flat_sequence=input_t)
--> 691     call_cell = lambda: cell(input_t, state)
    692 
    693     if sequence_length is not None:

C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\rnn\python\ops\core_rnn_cell_impl.py in __call__(self, inputs, state, scope)
    233   def __call__(self, inputs, state, scope=None):
    234     """Long short-term memory cell (LSTM)."""
--> 235     with _checked_scope(self, scope or "basic_lstm_cell", reuse=self._reuse):
    236       # Parameters of gates are concatenated into one multiply for efficiency.
    237       if self._state_is_tuple:

C:\Program Files\Anaconda3\envs\tensorflow\lib\contextlib.py in __enter__(self)
     57     def __enter__(self):
     58         try:
---> 59             return next(self.gen)
     60         except StopIteration:
     61             raise RuntimeError("generator didn't yield") from None

C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\rnn\python\ops\core_rnn_cell_impl.py in _checked_scope(cell, scope, reuse, **kwargs)
     91             "To share the weights of an RNNCell, simply "
     92             "reuse it in your second calculation, or create a new one with "
---> 93             "the argument reuse=True." % (scope_name, type(cell).__name__))
     94 
     95     # Everything is OK.  Update the cell's scope and yield it.

ValueError: Attempt to have a second RNNCell use the weights of a variable scope that already has weights: 'rnn/basic_lstm_cell'; and the cell was not constructed as BasicLSTMCell(..., reuse=True).  To share the weights of an RNNCell, simply reuse it in your second calculation, or create a new one with the argument reuse=True.

**Comment by ryukidong** [comment]
Sorry!!
It's my typing mistake.

**Comment by Jungmo** [comment]
What was the typo? Though I copied and pasted the script, it occurs same error you wrote.

**Comment by ryukidong** [comment]
When the error occurs, restart Jupyter Notebook then clear problem.





*From:* Jungmo Ahn [mailto:notifications@github.com]
*Sent:* Saturday, August 5, 2017 6:13 PM
*To:* hunkim/DeepLearningZeroToAll
*Cc:* ryukidong; State change
*Subject:* Re: [hunkim/DeepLearningZeroToAll] 12-5-rnn has compile error at
making dynamic_rnn (#177)



What was the typo? Though I copied and pasted the script, it occurs same
error you wrote.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/hunkim/DeepLearningZeroToAll/issues/177#issuecomment-320432473>,
or mute the thread
