### ISSUE TITLE
Issue on minmax scaling with whole data

### ISSUE THREAD

**Issue by bych-lee** [hunkim/DeepLearningZeroToAll#187]
In <lab-12-5-rnn_stock_prediction.py>, minmax scaling is carried out by using whole data.
However, it is assumed that we can only see the training data, and the test data is hidden.
So, I think we should correct the first part of the code as follows:

-------------------------------------------------------------------------------------------------------

```python
xy = np.loadtxt('data-02-stock_daily.csv', delimiter=',')
xy = xy[::-1]
train_size = int(len(xy) * 0.7)
train = np.array(xy[0:train_size])
test = np.array(xy[train_size:len(data)])

def MinMaxScaler(data):
    numerator = data - np.min(train, 0)
    denominator = np.max(train, 0) - np.min(train, 0)
    return numerator / (denominator + 1e-7)

xy_train = MinMaxScaler(train)
xy_test = MinMaxScaler(test)

list_trainX = []
list_trainY = []
for i in range(0, len(xy_train) - seq_length):
    x = xy_train[i:i + seq_length]
    y = xy_train[:,[-1]][i + seq_length]
    list_trainX.append(x)
    list_trainY.append(y)

list_testX = []
list_testY = []
for i in range(0, len(xy_test) - seq_length):
    x = xy_test[i:i + seq_length]
    y = xy_test[:,[-1]][i + seq_length]
    list_testX.append(x)
    list_testY.append(y)

trainX, testX = np.array(list_trainX), np.array(list_testX)
trainY, testY = np.array(list_trainY), np.array(list_testY)
```

**Comment by kkweon** [comment]
Yes, you are right except

```python
y = xy_train[:,[-1]][i + seq_length] # what's wrong with `y = xy_train[i + seq_length]`?
```
Plus, `MinMaxScaler` should be replaced by `sklearn.preprocessing.MinMaxScaler` (#109).



You are welcome to send a PR.

**Comment by prinsommer** [comment]
"xy_train" is a matrix. So, "xy_train[i+seq_length]" would be a row vector.

Here, we want to refer the last component of the row vector, which is closing price.

So, I wrote as "xy_train[:,[-1]][i + seq_length]".

(By the way, what does PR stand for? I am new to github.)

**Comment by kkweon** [comment]
- if that's the case, 
then 

`y = xy_train[i + seq_length, -1]` is preferred.

- PR stands for a pull request.
  - You can read more in [CONTRINGBUTING.md](https://github.com/hunkim/DeepLearningZeroToAll/blob/master/CONTRIBUTING.md)

**Comment by prinsommer** [comment]
That's better, and I will try PR.

Thank you for your kind reply.

**Comment by prinsommer** [comment]
It seems that `y=xy_train[:,[-1]][i + seq_length]` makes trainY be shaped (#rows, 1),

and `y = xy_train[i + seq_length, -1]` makes trainY be shaped (#rows, ), doesn't it?

**Comment by kkweon** [comment]
then you can do `y = xy_train[i + seq_length, [-1]]`

the reason why `y=xy_train[:,[-1]] [i + seq_length]  ` is bad is that you are calling the entire column by calling `xy_train[:, [-1]]`

**Comment by prinsommer** [comment]
I see. I am learning a lot from you today. Thank you.:D

**Comment by prinsommer** [comment]
@kkweon Why should I replace `MinMaxScaler` by `sklearn.preprocessing.MinMaxScaler`? 
In the code, I just defined a function called "MinMaxScaler".

**Comment by kkweon** [comment]
Because it is a code smell. 

- It is not consistent with other files.
- It is not following the PEP8 either.
 
The discussion was done in #109. 
Hashtag followed by a number refers to the related issue.
