### ISSUE TITLE
lab-11-1-mnist_cnn.py 

### ISSUE THREAD

**Issue by tigon7476** [hunkim/DeepLearningZeroToAll#189]
File "D:/my_mnist_cnn.py", line 137, in <module>
    initializer=tf.contrib.layers.xavier_initializer())

ValueError: Variable W3 already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

그대로 따라하던 중, W3 = tf.get_variable() 부분에서 위와 같은 오류가 발생합니다.
처음 실행할 때는 괜찮은 데, 2번 째 실행부터 오류가 발생합니다. 

Spyder 3.1.4, Python 3.6 윈도우버전입니다.

**Comment by kkweon** [comment]
해당 질문은 이곳과는 상관없는 텐서플로우 질문이기 때문에 텐서플로우 페이스북 그룹에 물어보시는게 좋으실 것 같네요.
에러 메세지는 말그대로 variable w3이 존재하는데 다시 만들려고 해서 발생하는 문제입니다.
