### ISSUE TITLE
In lab-06-1, warnings are occureed

### ISSUE THREAD

**Issue by Jinhkiim** [hunkim/DeepLearningZeroToAll#194]
I have run lab 6-1. (python 3.6.2, tf 1.3 (using gpu), anaconda, win10 x64)
The following warning appeared.

> WARNING:tensorflow:From lab-06-1-softmax_classifier.py:51: arg_max (from tensorflow.python.ops.gen_math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `argmax` instead
[[  1.37063488e-03   9.98620391e-01   8.96136680e-06]] [1]

>WARNING:tensorflow:From lab-06-1-softmax_classifier.py:56: arg_max (from tensorflow.python.ops.gen_math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `argmax` instead
[[ 0.9315275   0.06260772  0.00586479]] [0]

>WARNING:tensorflow:From lab-06-1-softmax_classifier.py:61: arg_max (from tensorflow.python.ops.gen_math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `argmax` instead
[[  1.23516228e-08   3.30023380e-04   9.99670029e-01]] [2]

>WARNING:tensorflow:From lab-06-1-softmax_classifier.py:67: arg_max (from tensorflow.python.ops.gen_math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `argmax` instead

It is a warning that _argmax()_ should be used instead of _arg_max()_.
Someday you will need to modify the code, and the code has been run normally with _argmax()_.
I do not know how to push that code snippet into the repository, so I leave a post on this bulletin board.

**Comment by kkweon** [comment]
Good catch! Thanks for letting us know here. The patch is coming soon. Thanks!
