### ISSUE TITLE
possible look-ahead bias in  lab-12-5-rnn-stock

### ISSUE THREAD

**Issue by goodcheer** [hunkim/DeepLearningZeroToAll#214]
In current code, the whole data are scaled and then partitioned into train and test set,
which utilize future (test set) information when scaling past (train set) data. 
```
# Open, High, Low, Volume, Close
xy = np.loadtxt('data-02-stock_daily.csv', delimiter=',')
xy = xy[::-1]  # reverse order (chronically ordered)
xy = MinMaxScaler(xy)
x = xy
y = xy[:, [-1]]  # Close as label

# build a dataset
dataX = []
dataY = []
for i in range(0, len(y) - seq_length):
    _x = x[i:i + seq_length]
    _y = y[i + seq_length]  # Next close price
#     print(_x, "->", _y)
    dataX.append(_x)
    dataY.append(_y)

# train/test split
train_size = int(len(dataY) * 0.7)
test_size = len(dataY) - train_size
trainX, testX = np.array(dataX[0:train_size]), np.array(
    dataX[train_size:len(dataX)])
trainY, testY = np.array(dataY[0:train_size]), np.array(
    dataY[train_size:len(dataY)])
````
However,  i think it makes more sense to scale train and test set separately; since you would not get data of future (test set), when scaling current and past data (train set).

In real life scenarios, we know nothing about future data at the point of making prediction. If we include data in the testing set to compute the sample mean, we would inadvently introduce future information into historical data, which would render the prediction useless. [comment from](http://disq.us/p/1qow0dc)

Therefore, I think the whole process should be rather like:

- **train/test partition** -> **scale on each set** -> **build dataset**

## Comparing results of two different Preprocessing
1. Original

![original](https://user-images.githubusercontent.com/31753713/45723282-87989f80-bb7e-11e8-9fc9-2975083e6e72.png)

2. Proposed

![proposed](https://user-images.githubusercontent.com/31753713/45723135-ca0dac80-bb7d-11e8-86a6-27762f314c0c.png)

More details at
[lab-12-5-rnn_stock_issue_campare.ipynb](https://github.com/goodcheer/etc/blob/master/lab-12-5-rnn_stock_issue_compare.ipynb)

**Comment by kkweon** [comment]
You're absolutely right.
Just didn't have time to work on that lately.

If you can send a PR, it'd be greatly appreciated.

**Comment by goodcheer** [comment]
Thank you. It is my great pleasure to do a PR.

**Comment by kkweon** [comment]
Closing as #215 was merged
