### ISSUE TITLE
lab-02-2-linear_regression_feed.py need `global_variables_initializer`

### ISSUE THREAD

**Issue by tucan9389** [hunkim/DeepLearningZeroToAll#243]
Hi, I'm a student and I have found some weird thing in `lab-02-2-linear_regression_feed.py`.
At line 41, there is second training with the new dataset(`{X: [1, 2, 3, 4, 5], Y: [2.1, 3.1, 4.1, 5.1, 6.1]}`) but `global_variables_initializer` isn't called before second training. 

Is there any reason for this?

**Comment by kkweon** [comment]
Instead of starting fresh, it is training on the top of the previous model. Sort of like simplified version of transfer learning

**Comment by tucan9389** [comment]
@kkweon Thanks for reply 👍
