### ISSUE TITLE
change comment cost -> cost/loss

### ISSUE THREAD

**Issue by FuZer** [hunkim/DeepLearningZeroToAll#27]
#26 
cost함수 부분 주석과 변수 명이 cost와 loss과 혼용 되어 있는 것을 확인했습니다. 
처음 시작하시는 분들이 용어에 혼동하지 않을까 생가되어 주석부분을 "cost/loss"로 둘 다 표기를 하였는데 어떠한가요?

**Comment by hunkim** [comment]
Done!
