### ISSUE TITLE
lab-12-5-rnn_stock_prediction.py

### ISSUE THREAD

**Issue by GzuPark** [hunkim/DeepLearningZeroToAll#47]
If anyone sees below when this file run,

```
from numpy._distributor_init import NUMPY_MKL  # requires numpy+mkl
ImportError: cannot import name 'NUMPY_MKL'
```

Check out [ImportError: cannot import name NUMPY_MKL
](http://stackoverflow.com/questions/37267399/importerror-cannot-import-name-numpy-mkl) and solution to download [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy)

**Comment by hunkim** [comment]
Thanks. Do you know which numpy calls in the file cause this issue? Perhaps, we can replace it.

**Comment by GzuPark** [comment]
This problem occurred on the line `from sklearn.preprocessing import MinMaxScaler`.
If we edit `scaler = MinMaxScaler(feature_range=(0, 1))`, we can solve the problem another way.

**Comment by GzuPark** [comment]
```
def MinMaxScaler(data):
    num_row = np.shape(data)[0]
    num_col = np.shape(data)[1]
    array = np.zeros((num_row, num_col))
    for i in range(num_col):
        input = data[:,i]
        array[:,i] = (input - np.min(input)) / (np.max(input) - np.min(input))
    return array
```

If we use above function, we can do it!! Also, we don't need to use `sklearn.preprocessing` package.

**Comment by hunkim** [comment]
Cool. I think it's simple enough to add in the source code. Could you send
a PR?

Sung

**Comment by GzuPark** [comment]
#56 #57 Done.

**Comment by kkweon** [comment]
It can be done in two lines though.
```python
def MinMaxScaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) -  np.min(data, 0)
    return numerator/ (denominator + 1e-8) # noise should be added to prevent zero division
```

**Comment by hunkim** [comment]
Super.

**Comment by hunkim** [comment]
Can you come up with a pr?

**Comment by kkweon** [comment]
I can do that. The vectorized version is 8 times faster than the loop
```python
In [9]: %timeit -n 1000 MinMaxScaler1(A)
1000 loops, best of 3: 81.8 µs per loop

In [10]: %timeit -n 1000 MinMaxScaler2(A)
1000 loops, best of 3: 11.3 µs per loop
```

**Comment by hunkim** [comment]
I love it.

Sung
