### ISSUE TITLE
lab-03-2의 코드에 대해 질문있습니다.

### ISSUE THREAD

**Issue by bkRyusim** [hunkim/DeepLearningZeroToAll#69]
lab-03-2에서는 cost를
`cost = tf.reduce_sum(tf.square(hypothesis - Y))`
로 정의했는데,
`cost = tf.reduce_mean(tf.square(hypothesis - Y))`
으로 해야 정확한거죠? 모든 cost의 평균이니까...

물론 총합이나 평균이나 최솟값을 구하는데 영향을 주진 않겠지만
혹시 sum으로 해야만 하는 이유가 있는지 궁금해서 질문드립니다.

**Comment by hunkim** [comment]
`tf.reduce_mean` sounds right. Could you send a pull request?

Thanks!

**Comment by bkRyusim** [comment]
Thanks for your comment!
I'll make PR.
