### ISSUE TITLE
some changes in keras 2.x

### ISSUE THREAD

**Issue by skyer9** [hunkim/DeepLearningZeroToAll#78]
there are many changes in keras 2.x.

https://github.com/fchollet/keras/wiki/Keras-2.0-release-notes

some change is...
 - The nb_epoch argument has been renamed epochs everywhere
 - Any arguments (other than nb_epoch) prefixed with nb_ has been renamed to be prefixed with num_ instead.

and there is undocumented change.

```python
# from keras.utils.visualize_util import plot
from keras.utils.vis_utils import plot_model
```

**Comment by kkweon** [comment]
lol, I have completely forgotten we have Keras too.
Anyway, I'm sure @hunkim will say "Feel free to send a PR." 
Just let people know which one you are working.

**Comment by hunkim** [comment]
Please send us PRs

We will also have the pyTorch directory soon. :-)

**Comment by skyer9** [comment]
yes.
I will write some PR soon.

**Comment by hunkim** [comment]
Thanks! Please note that files in Keras are outdated. If you can update
them for Keras 2.0 and sync with TF lab files, it will be super wonderful!

Sung

**Comment by kkweon** [comment]
I updated the travis script such that it can run through all *.py files including TF and Keras.
Since it shows no errors, I will close this.
