### ISSUE TITLE
Naming of w_val, cost_val

### ISSUE THREAD

**Issue by Lewisxyz000** [hunkim/DeepLearningZeroToAll#97]
I think Lab03-1 can use **w_record**, **cost_record** or another name instead of **w_val** and **cost_val**
w_record and cost_record are hard to know at a glance

**Comment by hunkim** [comment]
Sounds good. Feel free to send a pr.

**Comment by Lewisxyz000** [comment]
I did two PR...but First PR is my mistake.. please close that #98 PR.
